### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by Masono03** [ribbon-studios/Puppets#11]
Hey i wanted to ask if this plugin will still get a update or if its been dropped? this would be so great to have for me and my friend since we are dancers in a club and syncing by countdown doesnt always work flawlessly and i found this but i cant install it since it says it needs a update :(

**Comment by cecilia-sanare** [comment]
Sorry! I primarily made this plugin for myself and once my use-case for it was gone my desire to maintain it also went with it. I did update it for Dalamud's v9 API, but I likely won't update it if it breaks again.
